var f = [];				
f[0]	= "v0.0.7";			
f[1]	= "01 Random Acts of Science.mp3";		
f[2]	= "02 Stone Cold Infusion.mp3";		
f[3]	= "03 Molecular Breakdown.mp3";		
f[4]	= "04 Particle Accelerations.mp3";		
f[5]	= "05 At the Edge of the Middle.mp3";		
f[6]	= "06 Atom Smashing.mp3";		
f[7]	= "07 In the Spirit Of.mp3";		
